# Generated by Django 4.1.6 on 2023-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avg_trade_quantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avg_trade_quantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
