# Generated by Django 4.1.6 on 2023-02-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('minimum_duration', models.IntegerField(max_length=5)),
                ('minimum_deposit', models.IntegerField(max_length=15)),
                ('garantie_percentage', models.IntegerField(max_length=5)),
                ('admin_client', models.IntegerField(max_length=5)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
    ]
