# Generated by Django 4.1.6 on 2023-02-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_leverage_contract_trading_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='leverage',
            field=models.CharField(choices=[('1:100', '1:100'), ('1:200', '1:200'), ('1:500', '1:500'), ('1:1000', '1:1000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='trading_timeframe',
            field=models.CharField(max_length=100),
        ),
    ]
