# Generated by Django 4.1.6 on 2023-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_leverage_alter_contract_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='leverage',
            field=models.CharField(max_length=100),
        ),
    ]
