# Generated by Django 4.1.6 on 2023-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='leverage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='trading_timeframe',
            field=models.CharField(max_length=10),
        ),
    ]
