# Generated by Django 4.1.6 on 2023-02-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_leverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='admin_client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='garantie_percentage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='level',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='trading_timeframe',
        ),
    ]
