# Generated by Django 4.1.6 on 2023-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_garantie_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_point_ruler',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='fourth_point_ruler',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='second_point_ruler',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='third_point_ruler',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
