# Generated by Django 4.1.6 on 2023-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_contract_first_point_ruler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bulima_share',
            field=models.CharField(blank=True, default='40', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_share',
            field=models.CharField(blank=True, default='60', max_length=50),
        ),
    ]
