# Generated by Django 4.1.6 on 2023-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_bulima_share_contract_client_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='minimum_deposit_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='minimum_deposit_en',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='minimum_duration_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='minimum_duration_en',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_ar',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_en',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
