# Generated by Django 4.1.6 on 2023-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_id', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
