# Generated by Django 4.1.6 on 2023-02-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account_id',
        ),
    ]
