# Generated by Django 4.1.6 on 2023-02-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='new_trades',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_in_trade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='remaining_days',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_profit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_trades',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
