# Generated by Django 4.1.6 on 2023-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='accountname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
