# Generated by Django 4.1.6 on 2023-02-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_user_account_accountname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='new_trades',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='percentage_in_trade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='remaining_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_trades',
            field=models.IntegerField(),
        ),
    ]
