# Generated by Django 4.1.6 on 2023-02-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_accountid_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='equity_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
