# Generated by Django 4.1.6 on 2023-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_email_account_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contractname',
            field=models.CharField(blank=True, default='A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static\\images\\MaskGroup1.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
