# Generated by Django 4.1.6 on 2023-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_contractname_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='MaskGroup1.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
